spring:
  application:
    name: test
  profiles:
    active: local
#  datasource:
#    url: jdbc:mysql://212.64.106.43:3306/kg_builder?characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
#    username: root
#    password: root@hiekn