spring:
  application:
    name: test
  profiles:
    active: local
#  datasource:
#    url: jdbc:mysql://192.168.1.7:3306/mjcms?characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
#    username: root
#    password: root@hiekn