spring:
  application:
    name: test
  profiles:
    active: local
#  datasource:
#    url: jdbc:mysql://192.168.1.159:3306/test?characterEncoding=utf8&amp;autoReconnect=true&amp;failOverReadOnly=false
#    username: root
#    password: root
